name: Conditional Demo

on:
  push:

jobs:

  demo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Print Branch
        run: echo "Current Branch is ${{ github.ref }}"

      - name: Main Branch Only
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying Production"

      - name: Always Runs
        if: always()
        run: echo "Cleanup Complete"