name: Secrets Demo

on:
  push:

env:
  PROJECT_NAME: GitHub Actions Demo

jobs:
  secret-demo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Print Project Name
        run: echo $PROJECT_NAME

      - name: Read Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo $MY_SECRET