name: Artifact Demo

on:
  push:

jobs:

  artifact-demo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Upload Report

        uses: actions/upload-artifact@v4

        with:
          name: project-report
          path: reports/report.txt