name: Checkout Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: List Files Before Checkout
        run: ls

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files After Checkout
        run: ls