name: Node.js CI Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Node Version
        run: node -v

      - name: Check NPM Version
        run: npm -v

      - name: List Project Files
        run: ls